Add OSTN02 link to OS website
OrdnanceSurvey/bng-transformations pull request #1
Opened 2016-04-12 08:45 UTC by snodnipper

inc. brief explanation.

2016-04-12 08:47 UTC, snodnipper commented
@dhardiman we should get slack notifications...didn't just now :( - and I did press that gorgeous green button.

2016-09-16 10:02 UTC, jskeates commented on README.md
> +In its original form OSTN02 consists of a plane 700km by 1250km grid of 1km resolution with an eastings shift and northing shift at each grid node.  The OSTNS02 file corrects the funamental BNG inacc
A couple of SPAG issues:`funamental` and `via mathematical function` (could be `via a mathematical function` or `via mathematical functions`)

2016-09-16 10:02 UTC, jskeates requested changes

2016-09-16 19:23 UTC, snodnipper commented on README.md
> +In its original form OSTN02 consists of a plane 700km by 1250km grid of 1km resolution with an eastings shift and northing shift at each grid node.  The OSTNS02 file corrects the funamental BNG inacc
+1 - roger that.  Updated.

2016-09-16 19:24 UTC, snodnipper commented on README.md
> +In its original form OSTN02 consists of a plane 700km by 1250km grid of 1km resolution with an eastings shift and northing shift at each grid node.  The OSTNS02 file corrects the funamental BNG inacc
With luck we can change this to OSTN15 soon.

2016-09-18 18:26 UTC, jskeates approved these changes

2016-09-18 18:27 UTC, merged